GET http://localhost:3000/cliente

###

POST http://localhost:3000/cliente/insert
Content-Type: application/json

{
    "username" : "admin",
    "password" : "1",
    "passwordConf" : "1",
    "nome" : "Teste",
    "email" : "aadmin@ipvc.pt"

}